environment:
  matrix:
#    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

build: false

install:
  - cmd: set PATH=%PYTHON%\;%PYTHON%\Scripts;%PATH%
  - cmd: echo %PATH%
  - cmd: dir %PYTHON%
  - python --version
  - "python -m pip install -U pip setuptools"
  - "python -m pip install Cython==0.28.3"
  - "python -m pip install -r requirements.txt"
  - "python -m pip install -r test-requirements.txt"

before_test:
  - "python utils/build_uic.py dgp/gui/ui"

test_script:
  - "pytest --cov=dgp tests"
