language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - python build/build_uic.py dgp/gui/ui
script:
  coverage run --source=dgp -m unittest discover
notifications:
    slack: polargeophysicsgroup:FO0QAgTctTetembHbEJq8hxP
