language: python
cache: pip
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y libgeos-dev
  - sudo apt-get install -y proj-bin
install:
  - pip install Cython==0.28.3
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - python utils/build_uic.py dgp/gui/ui
script:
  coverage run --source=dgp -m unittest discover
notifications:
    slack: polargeophysicsgroup:FO0QAgTctTetembHbEJq8hxP
