language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  coverage run --source=dgp -m unittest discover
notifications:
    slack: polargeophysicsgroup:FO0QAgTctTetembHbEJq8hxP
