# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dgp/gui/ui\add_flight_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewFlight(object):
    def setupUi(self, NewFlight):
        NewFlight.setObjectName("NewFlight")
        NewFlight.resize(550, 466)
        NewFlight.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/airborne"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewFlight.setWindowIcon(icon)
        NewFlight.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewFlight)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_input_layout = QtWidgets.QFormLayout()
        self.form_input_layout.setObjectName("form_input_layout")
        self.label_name = QtWidgets.QLabel(NewFlight)
        self.label_name.setObjectName("label_name")
        self.form_input_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.text_name = QtWidgets.QLineEdit(NewFlight)
        self.text_name.setObjectName("text_name")
        self.form_input_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_name)
        self.label_date = QtWidgets.QLabel(NewFlight)
        self.label_date.setObjectName("label_date")
        self.form_input_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_date)
        self.date_flight = QtWidgets.QDateEdit(NewFlight)
        self.date_flight.setCalendarPopup(True)
        self.date_flight.setDate(QtCore.QDate(2017, 1, 1))
        self.date_flight.setObjectName("date_flight")
        self.form_input_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_flight)
        self.label_meter = QtWidgets.QLabel(NewFlight)
        self.label_meter.setObjectName("label_meter")
        self.form_input_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_meter)
        self.label_uuid = QtWidgets.QLabel(NewFlight)
        self.label_uuid.setObjectName("label_uuid")
        self.form_input_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_uuid)
        self.combo_meter = QtWidgets.QComboBox(NewFlight)
        self.combo_meter.setObjectName("combo_meter")
        self.form_input_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.combo_meter)
        self.text_uuid = QtWidgets.QLineEdit(NewFlight)
        self.text_uuid.setEnabled(False)
        self.text_uuid.setReadOnly(True)
        self.text_uuid.setObjectName("text_uuid")
        self.form_input_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text_uuid)
        self.label_gravity = QtWidgets.QLabel(NewFlight)
        self.label_gravity.setObjectName("label_gravity")
        self.form_input_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_gravity)
        self.gravity_layout = QtWidgets.QHBoxLayout()
        self.gravity_layout.setObjectName("gravity_layout")
        self.path_gravity = QtWidgets.QLineEdit(NewFlight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_gravity.sizePolicy().hasHeightForWidth())
        self.path_gravity.setSizePolicy(sizePolicy)
        self.path_gravity.setBaseSize(QtCore.QSize(200, 0))
        self.path_gravity.setObjectName("path_gravity")
        self.gravity_layout.addWidget(self.path_gravity)
        self.cb_grav_format = QtWidgets.QComboBox(NewFlight)
        self.cb_grav_format.setObjectName("cb_grav_format")
        self.gravity_layout.addWidget(self.cb_grav_format)
        self.browse_gravity = QtWidgets.QToolButton(NewFlight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_gravity.sizePolicy().hasHeightForWidth())
        self.browse_gravity.setSizePolicy(sizePolicy)
        self.browse_gravity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.browse_gravity.setBaseSize(QtCore.QSize(50, 0))
        self.browse_gravity.setObjectName("browse_gravity")
        self.gravity_layout.addWidget(self.browse_gravity)
        self.form_input_layout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gravity_layout)
        self.label_gps = QtWidgets.QLabel(NewFlight)
        self.label_gps.setObjectName("label_gps")
        self.form_input_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_gps)
        self.gps_layout = QtWidgets.QHBoxLayout()
        self.gps_layout.setObjectName("gps_layout")
        self.path_gps = QtWidgets.QLineEdit(NewFlight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_gps.sizePolicy().hasHeightForWidth())
        self.path_gps.setSizePolicy(sizePolicy)
        self.path_gps.setBaseSize(QtCore.QSize(200, 0))
        self.path_gps.setObjectName("path_gps")
        self.gps_layout.addWidget(self.path_gps)
        self.cb_gps_format = QtWidgets.QComboBox(NewFlight)
        self.cb_gps_format.setObjectName("cb_gps_format")
        self.gps_layout.addWidget(self.cb_gps_format)
        self.browse_gps = QtWidgets.QToolButton(NewFlight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_gps.sizePolicy().hasHeightForWidth())
        self.browse_gps.setSizePolicy(sizePolicy)
        self.browse_gps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.browse_gps.setBaseSize(QtCore.QSize(50, 0))
        self.browse_gps.setObjectName("browse_gps")
        self.gps_layout.addWidget(self.browse_gps)
        self.form_input_layout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.gps_layout)
        self.verticalLayout.addLayout(self.form_input_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_flight_param = QtWidgets.QLabel(NewFlight)
        self.label_flight_param.setObjectName("label_flight_param")
        self.verticalLayout.addWidget(self.label_flight_param)
        self.flight_params = QtWidgets.QTableView(NewFlight)
        self.flight_params.setObjectName("flight_params")
        self.verticalLayout.addWidget(self.flight_params)
        self.label_message = QtWidgets.QLabel(NewFlight)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        self.buttons_dialog = QtWidgets.QDialogButtonBox(NewFlight)
        self.buttons_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons_dialog.setObjectName("buttons_dialog")
        self.verticalLayout.addWidget(self.buttons_dialog)
        self.label_name.setBuddy(self.text_name)
        self.label_date.setBuddy(self.date_flight)
        self.label_meter.setBuddy(self.combo_meter)
        self.label_gravity.setBuddy(self.path_gravity)
        self.label_gps.setBuddy(self.path_gps)

        self.retranslateUi(NewFlight)
        self.buttons_dialog.rejected.connect(NewFlight.reject)
        self.buttons_dialog.accepted.connect(NewFlight.accept)
        QtCore.QMetaObject.connectSlotsByName(NewFlight)
        NewFlight.setTabOrder(self.path_gravity, self.browse_gravity)
        NewFlight.setTabOrder(self.browse_gravity, self.path_gps)
        NewFlight.setTabOrder(self.path_gps, self.browse_gps)

    def retranslateUi(self, NewFlight):
        _translate = QtCore.QCoreApplication.translate
        NewFlight.setWindowTitle(_translate("NewFlight", "Add Flight"))
        self.label_name.setText(_translate("NewFlight", "Flight Name (Reference)*"))
        self.label_date.setText(_translate("NewFlight", "Flight Date"))
        self.date_flight.setDisplayFormat(_translate("NewFlight", "yyyy-MM-dd"))
        self.label_meter.setText(_translate("NewFlight", "Gravity Meter"))
        self.label_uuid.setText(_translate("NewFlight", "Flight UUID"))
        self.label_gravity.setText(_translate("NewFlight", "Gravity Data"))
        self.browse_gravity.setToolTip(_translate("NewFlight", "Browse"))
        self.browse_gravity.setStatusTip(_translate("NewFlight", "Browse"))
        self.browse_gravity.setText(_translate("NewFlight", "..."))
        self.label_gps.setText(_translate("NewFlight", "GPS Data"))
        self.browse_gps.setToolTip(_translate("NewFlight", "Browse"))
        self.browse_gps.setText(_translate("NewFlight", "..."))
        self.label_flight_param.setText(_translate("NewFlight", "Flight Parameters"))
        self.label_message.setText(_translate("NewFlight", "<html><head/><body><p align=\"right\">*required fields</p></body></html>"))

from dgp import resources_rc
