# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dgp/gui/ui\advanced_data_import.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdvancedImportData(object):
    def setupUi(self, AdvancedImportData):
        AdvancedImportData.setObjectName("AdvancedImportData")
        AdvancedImportData.resize(450, 418)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdvancedImportData.sizePolicy().hasHeightForWidth())
        AdvancedImportData.setSizePolicy(sizePolicy)
        AdvancedImportData.setSizeIncrement(QtCore.QSize(50, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdvancedImportData.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdvancedImportData)
        self.verticalLayout.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_data = QtWidgets.QGroupBox(AdvancedImportData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_data.sizePolicy().hasHeightForWidth())
        self.group_data.setSizePolicy(sizePolicy)
        self.group_data.setTitle("")
        self.group_data.setObjectName("group_data")
        self.formLayout = QtWidgets.QFormLayout(self.group_data)
        self.formLayout.setObjectName("formLayout")
        self.label_data_path = QtWidgets.QLabel(self.group_data)
        self.label_data_path.setObjectName("label_data_path")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_data_path)
        self.hbox_data_path = QtWidgets.QHBoxLayout()
        self.hbox_data_path.setObjectName("hbox_data_path")
        self.line_path = QtWidgets.QLineEdit(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_path.sizePolicy().hasHeightForWidth())
        self.line_path.setSizePolicy(sizePolicy)
        self.line_path.setReadOnly(True)
        self.line_path.setObjectName("line_path")
        self.hbox_data_path.addWidget(self.line_path)
        self.btn_browse = QtWidgets.QToolButton(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse.sizePolicy().hasHeightForWidth())
        self.btn_browse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_browse.setFont(font)
        self.btn_browse.setObjectName("btn_browse")
        self.hbox_data_path.addWidget(self.btn_browse)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.hbox_data_path)
        self.label_flight = QtWidgets.QLabel(self.group_data)
        self.label_flight.setObjectName("label_flight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_flight)
        self.combo_flights = QtWidgets.QComboBox(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_flights.sizePolicy().hasHeightForWidth())
        self.combo_flights.setSizePolicy(sizePolicy)
        self.combo_flights.setObjectName("combo_flights")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_flights)
        self.label_meter = QtWidgets.QLabel(self.group_data)
        self.label_meter.setObjectName("label_meter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_meter)
        self.combo_meters = QtWidgets.QComboBox(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_meters.sizePolicy().hasHeightForWidth())
        self.combo_meters.setSizePolicy(sizePolicy)
        self.combo_meters.setObjectName("combo_meters")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_meters)
        self.verticalLayout.addWidget(self.group_data)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_file_props = QtWidgets.QLabel(AdvancedImportData)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_file_props.setFont(font)
        self.label_file_props.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_file_props.setObjectName("label_file_props")
        self.verticalLayout.addWidget(self.label_file_props)
        self.grid_info_area = QtWidgets.QGridLayout()
        self.grid_info_area.setContentsMargins(5, -1, 5, 10)
        self.grid_info_area.setObjectName("grid_info_area")
        self.label_data_end = QtWidgets.QLabel(AdvancedImportData)
        self.label_data_end.setObjectName("label_data_end")
        self.grid_info_area.addWidget(self.label_data_end, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_line_count = QtWidgets.QLabel(AdvancedImportData)
        self.label_line_count.setObjectName("label_line_count")
        self.grid_info_area.addWidget(self.label_line_count, 4, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.field_line_count = QtWidgets.QLabel(AdvancedImportData)
        self.field_line_count.setObjectName("field_line_count")
        self.grid_info_area.addWidget(self.field_line_count, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.field_fsize = QtWidgets.QLabel(AdvancedImportData)
        self.field_fsize.setObjectName("field_fsize")
        self.grid_info_area.addWidget(self.field_fsize, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.check_trim = QtWidgets.QCheckBox(AdvancedImportData)
        self.check_trim.setEnabled(False)
        self.check_trim.setObjectName("check_trim")
        self.grid_info_area.addWidget(self.check_trim, 1, 0, 1, 1)
        self.dte_data_end = QtWidgets.QDateTimeEdit(AdvancedImportData)
        self.dte_data_end.setEnabled(False)
        self.dte_data_end.setObjectName("dte_data_end")
        self.grid_info_area.addWidget(self.dte_data_end, 0, 3, 1, 1)
        self.label_col_count = QtWidgets.QLabel(AdvancedImportData)
        self.label_col_count.setObjectName("label_col_count")
        self.grid_info_area.addWidget(self.label_col_count, 3, 2, 1, 1)
        self.dte_data_start = QtWidgets.QDateTimeEdit(AdvancedImportData)
        self.dte_data_start.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_data_start.sizePolicy().hasHeightForWidth())
        self.dte_data_start.setSizePolicy(sizePolicy)
        self.dte_data_start.setObjectName("dte_data_start")
        self.grid_info_area.addWidget(self.dte_data_start, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_data_start = QtWidgets.QLabel(AdvancedImportData)
        self.label_data_start.setObjectName("label_data_start")
        self.grid_info_area.addWidget(self.label_data_start, 0, 0, 1, 1)
        self.label_file_size = QtWidgets.QLabel(AdvancedImportData)
        self.label_file_size.setObjectName("label_file_size")
        self.grid_info_area.addWidget(self.label_file_size, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.field_col_count = QtWidgets.QLabel(AdvancedImportData)
        self.field_col_count.setObjectName("field_col_count")
        self.grid_info_area.addWidget(self.field_col_count, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.grid_info_area.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.grid_info_area)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.hbox_editcols = QtWidgets.QHBoxLayout()
        self.hbox_editcols.setObjectName("hbox_editcols")
        self.label_data_fmt = QtWidgets.QLabel(AdvancedImportData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_fmt.sizePolicy().hasHeightForWidth())
        self.label_data_fmt.setSizePolicy(sizePolicy)
        self.label_data_fmt.setObjectName("label_data_fmt")
        self.hbox_editcols.addWidget(self.label_data_fmt)
        self.cb_data_fmt = QtWidgets.QComboBox(AdvancedImportData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_data_fmt.sizePolicy().hasHeightForWidth())
        self.cb_data_fmt.setSizePolicy(sizePolicy)
        self.cb_data_fmt.setObjectName("cb_data_fmt")
        self.hbox_editcols.addWidget(self.cb_data_fmt)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.hbox_editcols.addItem(spacerItem3)
        self.btn_edit_cols = QtWidgets.QPushButton(AdvancedImportData)
        self.btn_edit_cols.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit_cols.sizePolicy().hasHeightForWidth())
        self.btn_edit_cols.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_edit_cols.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/assets/meter_config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_cols.setIcon(icon1)
        self.btn_edit_cols.setObjectName("btn_edit_cols")
        self.hbox_editcols.addWidget(self.btn_edit_cols)
        self.verticalLayout.addLayout(self.hbox_editcols)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_msg = QtWidgets.QLabel(AdvancedImportData)
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.verticalLayout.addWidget(self.label_msg)
        self.btn_dialog = QtWidgets.QDialogButtonBox(AdvancedImportData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dialog.sizePolicy().hasHeightForWidth())
        self.btn_dialog.setSizePolicy(sizePolicy)
        self.btn_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.btn_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_dialog.setCenterButtons(False)
        self.btn_dialog.setObjectName("btn_dialog")
        self.verticalLayout.addWidget(self.btn_dialog)
        self.label_data_path.setBuddy(self.line_path)
        self.label_flight.setBuddy(self.combo_flights)
        self.label_meter.setBuddy(self.combo_meters)
        self.label_data_end.setBuddy(self.dte_data_end)
        self.label_data_start.setBuddy(self.dte_data_start)
        self.label_data_fmt.setBuddy(self.cb_data_fmt)

        self.retranslateUi(AdvancedImportData)
        self.btn_dialog.accepted.connect(AdvancedImportData.accept)
        self.btn_dialog.rejected.connect(AdvancedImportData.reject)
        QtCore.QMetaObject.connectSlotsByName(AdvancedImportData)

    def retranslateUi(self, AdvancedImportData):
        _translate = QtCore.QCoreApplication.translate
        AdvancedImportData.setWindowTitle(_translate("AdvancedImportData", "Advanced Import"))
        self.label_data_path.setText(_translate("AdvancedImportData", "Path*"))
        self.line_path.setPlaceholderText(_translate("AdvancedImportData", "Browse to File"))
        self.btn_browse.setText(_translate("AdvancedImportData", "..."))
        self.label_flight.setText(_translate("AdvancedImportData", "Flight"))
        self.label_meter.setText(_translate("AdvancedImportData", "Meter"))
        self.label_file_props.setText(_translate("AdvancedImportData", "File Properties:"))
        self.label_data_end.setText(_translate("AdvancedImportData", "Data End"))
        self.label_line_count.setText(_translate("AdvancedImportData", "Line Count"))
        self.field_line_count.setText(_translate("AdvancedImportData", "0"))
        self.field_fsize.setText(_translate("AdvancedImportData", "0 Mib"))
        self.check_trim.setText(_translate("AdvancedImportData", "Trim"))
        self.label_col_count.setText(_translate("AdvancedImportData", "Column Count:"))
        self.label_data_start.setText(_translate("AdvancedImportData", "Data Start"))
        self.label_file_size.setText(_translate("AdvancedImportData", "File Size (Mib)"))
        self.field_col_count.setText(_translate("AdvancedImportData", "0"))
        self.label_data_fmt.setText(_translate("AdvancedImportData", "Column Format:"))
        self.btn_edit_cols.setText(_translate("AdvancedImportData", "Edit Columns"))

from dgp import resources_rc
