# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dgp/gui/ui\edit_import_view.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(304, 296)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_instruction = QtWidgets.QLabel(Dialog)
        self.label_instruction.setObjectName("label_instruction")
        self.verticalLayout.addWidget(self.label_instruction)
        self.hbox_tools = QtWidgets.QHBoxLayout()
        self.hbox_tools.setObjectName("hbox_tools")
        self.btn_autosize = QtWidgets.QToolButton(Dialog)
        self.btn_autosize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/AutosizeStretch_16x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_autosize.setIcon(icon)
        self.btn_autosize.setObjectName("btn_autosize")
        self.hbox_tools.addWidget(self.btn_autosize)
        self.chb_has_header = QtWidgets.QCheckBox(Dialog)
        self.chb_has_header.setObjectName("chb_has_header")
        self.hbox_tools.addWidget(self.chb_has_header)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.hbox_tools.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.cob_field_set = QtWidgets.QComboBox(Dialog)
        self.cob_field_set.setObjectName("cob_field_set")
        self.hbox_tools.addWidget(self.cob_field_set)
        self.verticalLayout.addLayout(self.hbox_tools)
        self.table_col_edit = QtWidgets.QTableView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_col_edit.sizePolicy().hasHeightForWidth())
        self.table_col_edit.setSizePolicy(sizePolicy)
        self.table_col_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_col_edit.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.table_col_edit.setObjectName("table_col_edit")
        self.table_col_edit.horizontalHeader().setVisible(True)
        self.table_col_edit.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table_col_edit)
        self.label_msg = QtWidgets.QLabel(Dialog)
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.verticalLayout.addWidget(self.label_msg)
        self.hbox_dlg_btns = QtWidgets.QHBoxLayout()
        self.hbox_dlg_btns.setObjectName("hbox_dlg_btns")
        self.btn_reset = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setObjectName("btn_reset")
        self.hbox_dlg_btns.addWidget(self.btn_reset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_dlg_btns.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setObjectName("btn_cancel")
        self.hbox_dlg_btns.addWidget(self.btn_cancel)
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_confirm.sizePolicy().hasHeightForWidth())
        self.btn_confirm.setSizePolicy(sizePolicy)
        self.btn_confirm.setObjectName("btn_confirm")
        self.hbox_dlg_btns.addWidget(self.btn_confirm)
        self.verticalLayout.addLayout(self.hbox_dlg_btns)

        self.retranslateUi(Dialog)
        self.btn_cancel.clicked.connect(Dialog.reject)
        self.btn_confirm.clicked.connect(Dialog.accept)
        self.btn_autosize.clicked.connect(self.table_col_edit.resizeColumnsToContents)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data Preview"))
        self.label_instruction.setText(_translate("Dialog", "Double Click Column Headers to Change Order"))
        self.btn_autosize.setToolTip(_translate("Dialog", "Autosize Column Widths"))
        self.chb_has_header.setToolTip(_translate("Dialog", "Check to skip first line in file"))
        self.chb_has_header.setText(_translate("Dialog", "Has header"))
        self.label.setText(_translate("Dialog", "Field Set:"))
        self.btn_reset.setText(_translate("Dialog", "Reset"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.btn_confirm.setText(_translate("Dialog", "Confirm"))

from dgp import resources_rc
