# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dgp/gui/ui\project_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setSizeIncrement(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dgs"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAccessibleName("")
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prj_type_list = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_type_list.sizePolicy().hasHeightForWidth())
        self.prj_type_list.setSizePolicy(sizePolicy)
        self.prj_type_list.setMinimumSize(QtCore.QSize(0, 0))
        self.prj_type_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.prj_type_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prj_type_list.setLineWidth(1)
        self.prj_type_list.setIconSize(QtCore.QSize(20, 20))
        self.prj_type_list.setViewMode(QtWidgets.QListView.ListMode)
        self.prj_type_list.setUniformItemSizes(True)
        self.prj_type_list.setObjectName("prj_type_list")
        self.horizontalLayout_4.addWidget(self.prj_type_list)
        self.vbox_main = QtWidgets.QVBoxLayout()
        self.vbox_main.setSpacing(3)
        self.vbox_main.setObjectName("vbox_main")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(0, 25))
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.hbox_project_name = QtWidgets.QHBoxLayout()
        self.hbox_project_name.setObjectName("hbox_project_name")
        self.prj_name = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_name.sizePolicy().hasHeightForWidth())
        self.prj_name.setSizePolicy(sizePolicy)
        self.prj_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prj_name.setFont(font)
        self.prj_name.setObjectName("prj_name")
        self.hbox_project_name.addWidget(self.prj_name)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.hbox_project_name)
        self.label_dir = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dir.sizePolicy().hasHeightForWidth())
        self.label_dir.setSizePolicy(sizePolicy)
        self.label_dir.setMinimumSize(QtCore.QSize(0, 25))
        self.label_dir.setObjectName("label_dir")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_dir)
        self.hbox_form_directory = QtWidgets.QHBoxLayout()
        self.hbox_form_directory.setContentsMargins(-1, 0, -1, 0)
        self.hbox_form_directory.setSpacing(2)
        self.hbox_form_directory.setObjectName("hbox_form_directory")
        self.prj_dir = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_dir.sizePolicy().hasHeightForWidth())
        self.prj_dir.setSizePolicy(sizePolicy)
        self.prj_dir.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prj_dir.setFont(font)
        self.prj_dir.setFrame(True)
        self.prj_dir.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.prj_dir.setClearButtonEnabled(False)
        self.prj_dir.setObjectName("prj_dir")
        self.hbox_form_directory.addWidget(self.prj_dir)
        self.prj_browse = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_browse.sizePolicy().hasHeightForWidth())
        self.prj_browse.setSizePolicy(sizePolicy)
        self.prj_browse.setObjectName("prj_browse")
        self.hbox_form_directory.addWidget(self.prj_browse)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hbox_form_directory)
        self.label_required = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_required.setFont(font)
        self.label_required.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_required.setObjectName("label_required")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_required)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.prj_properties = QtWidgets.QPushButton(Dialog)
        self.prj_properties.setEnabled(False)
        self.prj_properties.setObjectName("prj_properties")
        self.horizontalLayout_2.addWidget(self.prj_properties)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.vbox_main.addLayout(self.formLayout)
        self.label_msg = QtWidgets.QLabel(Dialog)
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.vbox_main.addWidget(self.label_msg, 0, QtCore.Qt.AlignLeft)
        self.vbox_advanced_controls = QtWidgets.QVBoxLayout()
        self.vbox_advanced_controls.setObjectName("vbox_advanced_controls")
        self.widget_advanced = QtWidgets.QWidget(Dialog)
        self.widget_advanced.setEnabled(False)
        self.widget_advanced.setObjectName("widget_advanced")
        self.vbox_advanced_controls.addWidget(self.widget_advanced)
        self.vbox_main.addLayout(self.vbox_advanced_controls)
        self.hbox_dialog_buttons = QtWidgets.QHBoxLayout()
        self.hbox_dialog_buttons.setObjectName("hbox_dialog_buttons")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_dialog_buttons.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_cancel.setObjectName("btn_cancel")
        self.hbox_dialog_buttons.addWidget(self.btn_cancel)
        self.btn_create = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create.sizePolicy().hasHeightForWidth())
        self.btn_create.setSizePolicy(sizePolicy)
        self.btn_create.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_create.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_create.setObjectName("btn_create")
        self.hbox_dialog_buttons.addWidget(self.btn_create)
        self.vbox_main.addLayout(self.hbox_dialog_buttons)
        self.horizontalLayout_4.addLayout(self.vbox_main)
        self.label_name.setBuddy(self.prj_name)
        self.label_dir.setBuddy(self.prj_dir)

        self.retranslateUi(Dialog)
        self.btn_cancel.clicked.connect(Dialog.reject)
        self.prj_properties.clicked.connect(self.widget_advanced.show)
        self.btn_create.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_create, self.prj_type_list)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create New Project"))
        self.label_name.setText(_translate("Dialog", "Project Name:*"))
        self.label_dir.setText(_translate("Dialog", "Project Directory:*"))
        self.prj_browse.setText(_translate("Dialog", "..."))
        self.label_required.setText(_translate("Dialog", " required fields*"))
        self.prj_properties.setText(_translate("Dialog", "Properties"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.btn_create.setText(_translate("Dialog", "Create"))

from dgp import resources_rc
