# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dgp/gui/ui\splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Launcher(object):
    def setupUi(self, Launcher):
        Launcher.setObjectName("Launcher")
        Launcher.resize(604, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Launcher.sizePolicy().hasHeightForWidth())
        Launcher.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/geoid"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Launcher.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Launcher)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(Launcher)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_globeico = QtWidgets.QLabel(Launcher)
        self.label_globeico.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_globeico.setText("")
        self.label_globeico.setPixmap(QtGui.QPixmap(":/images/geoid"))
        self.label_globeico.setScaledContents(True)
        self.label_globeico.setAlignment(QtCore.Qt.AlignCenter)
        self.label_globeico.setObjectName("label_globeico")
        self.verticalLayout.addWidget(self.label_globeico, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_license = QtWidgets.QLabel(Launcher)
        self.label_license.setObjectName("label_license")
        self.verticalLayout.addWidget(self.label_license)
        self.group_recent = QtWidgets.QGroupBox(Launcher)
        self.group_recent.setTitle("")
        self.group_recent.setFlat(True)
        self.group_recent.setCheckable(False)
        self.group_recent.setObjectName("group_recent")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_recent)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_recent = QtWidgets.QLabel(self.group_recent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_recent.sizePolicy().hasHeightForWidth())
        self.label_recent.setSizePolicy(sizePolicy)
        self.label_recent.setObjectName("label_recent")
        self.horizontalLayout_2.addWidget(self.label_recent)
        self.btn_clear_recent = QtWidgets.QPushButton(self.group_recent)
        self.btn_clear_recent.setBaseSize(QtCore.QSize(100, 0))
        self.btn_clear_recent.setObjectName("btn_clear_recent")
        self.horizontalLayout_2.addWidget(self.btn_clear_recent)
        self.verticalLayout.addWidget(self.group_recent)
        self.list_projects = QtWidgets.QListWidget(Launcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_projects.sizePolicy().hasHeightForWidth())
        self.list_projects.setSizePolicy(sizePolicy)
        self.list_projects.setObjectName("list_projects")
        self.verticalLayout.addWidget(self.list_projects)
        self.group_btns = QtWidgets.QGroupBox(Launcher)
        self.group_btns.setTitle("")
        self.group_btns.setAlignment(QtCore.Qt.AlignCenter)
        self.group_btns.setFlat(True)
        self.group_btns.setObjectName("group_btns")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_btns)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_newproject = QtWidgets.QPushButton(self.group_btns)
        self.btn_newproject.setObjectName("btn_newproject")
        self.horizontalLayout.addWidget(self.btn_newproject)
        self.btn_browse = QtWidgets.QPushButton(self.group_btns)
        self.btn_browse.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout.addWidget(self.btn_browse)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_error = QtWidgets.QLabel(self.group_btns)
        self.label_error.setMinimumSize(QtCore.QSize(40, 0))
        self.label_error.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.horizontalLayout.addWidget(self.label_error)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.dialog_buttons = QtWidgets.QDialogButtonBox(self.group_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_buttons.sizePolicy().hasHeightForWidth())
        self.dialog_buttons.setSizePolicy(sizePolicy)
        self.dialog_buttons.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.dialog_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialog_buttons.setObjectName("dialog_buttons")
        self.horizontalLayout.addWidget(self.dialog_buttons)
        self.verticalLayout.addWidget(self.group_btns)
        self.actionbrowse = QtWidgets.QAction(Launcher)
        self.actionbrowse.setObjectName("actionbrowse")

        self.retranslateUi(Launcher)
        self.dialog_buttons.rejected.connect(Launcher.reject)
        self.dialog_buttons.accepted.connect(Launcher.accept)
        QtCore.QMetaObject.connectSlotsByName(Launcher)

    def retranslateUi(self, Launcher):
        _translate = QtCore.QCoreApplication.translate
        Launcher.setWindowTitle(_translate("Launcher", "Dynamic Gravity Processor"))
        self.label_title.setText(_translate("Launcher", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#55557f;\">Dynamic Gravity Processor</span></p></body></html>"))
        self.label_license.setText(_translate("Launcher", "<html><head/><body><p align=\"center\">Version 0.1</p><p align=\"center\">Licensed under the Apache-2.0 License</p></body></html>"))
        self.label_recent.setText(_translate("Launcher", "Open Recent Project:"))
        self.btn_clear_recent.setText(_translate("Launcher", "Clear Recent"))
        self.btn_newproject.setText(_translate("Launcher", "&New Project"))
        self.btn_browse.setWhatsThis(_translate("Launcher", "Browse for a project"))
        self.btn_browse.setText(_translate("Launcher", "&Browse..."))
        self.actionbrowse.setText(_translate("Launcher", "browse"))
        self.actionbrowse.setShortcut(_translate("Launcher", "Ctrl+O"))

from dgp import resources_rc
